# -*- coding: utf-8 -*-
"""Credit Card Default

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104UaLsl_V92onqhddzhdIZpVPaRSvXwj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Data Preprocessing**"""

credit_card = pd.read_csv('UCI_Credit_Card.csv')
credit_card.head()

# Drop ID
credit_card = credit_card.drop('ID', axis = 1)
credit_card.head()

# One Hot Encoding on SEX variable
credit_card = pd.get_dummies(credit_card, columns = ['SEX'])
credit_card.head()

# One Hot Encoding for EDUCATION variable but let's rename columns too
credit_card = pd.get_dummies(credit_card, columns = ['EDUCATION'])
credit_card = credit_card.drop('EDUCATION_0', axis = 1)
credit_card.head()

# One Hot Encoding on MARRIAGE variable
credit_card = pd.get_dummies(credit_card, columns = ['MARRIAGE'])
credit_card.head()

credit_card.columns

# scaling and train test split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Split first
X_temp = credit_card.drop('default.payment.next.month', axis=1)
y = credit_card['default.payment.next.month']

X_train, X_temp, y_train, y_temp = train_test_split(X_temp, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

# Scale only numerical features in TRAIN, then transform VAL & TEST
scaler = StandardScaler()

X_train_num = pd.DataFrame(scaler.fit_transform(X_train[numerical_columns]), columns=numerical_columns, index=X_train.index)
X_val_num = pd.DataFrame(scaler.transform(X_val[numerical_columns]), columns=numerical_columns, index=X_val.index)
X_test_num = pd.DataFrame(scaler.transform(X_test[numerical_columns]), columns=numerical_columns, index=X_test.index)

# Concatenate categorical features (already 0/1)
X_train_final = pd.concat([X_train_num, X_train[categorical_columns[1:]]], axis=1)  # exclude target col
X_val_final = pd.concat([X_val_num, X_val[categorical_columns[1:]]], axis=1)
X_test_final = pd.concat([X_test_num, X_test[categorical_columns[1:]]], axis=1)

"""# **Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, confusion_matrix

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train_final, y_train)

y_pred_lr = logreg.predict(X_test_final)
y_prob_lr = logreg.predict_proba(X_test_final)[:, 1]

accuracy_lr = accuracy_score(y_test, y_pred_lr)
classification_report_lr = classification_report(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_prob_lr)
confusion_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print("-- Logistic Regression Results --")
print("\nAccuracy: ", accuracy_lr)
print("\nClassification Report: \n", classification_report_lr)
print("\nROC AUC Score: ", roc_auc_lr)
print("\nConfusion Matrix: \n", confusion_matrix_lr)

"""# **Neural Network**"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, classification_report
from sklearn.utils.class_weight import compute_class_weight

weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weights = {0: weights[0], 1: weights[1]}

nn_model = Sequential([Dense(64, input_dim=X_train_final.shape[1], activation='relu'), Dropout(0.2), Dense(32, activation='relu'), Dense(1, activation='sigmoid')])


nn_model.compile(optimizer = Adam(learning_rate = 0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])

history = nn_model.fit(X_train_final, y_train, validation_data = (X_val_final, y_val), epochs = 50, batch_size = 32, class_weight = class_weights)

y_prob_nn = nn_model.predict(X_test_final).flatten()
y_pred_nn = (y_prob_nn > 0.4).astype(int)

accuracy_nn = accuracy_score(y_test, y_pred_nn)
confusion_matrix_nn = confusion_matrix(y_test, y_pred_nn)
roc_auc_nn = roc_auc_score(y_test, y_pred_nn)
classification_report_nn = classification_report(y_test, y_pred_nn)

print("-- Neural Network Results --")
print("\nAccuracy: ", accuracy_nn)
print("\nClassification Report: \n", classification_report_nn)
print("\nROC AUC Score: ", roc_auc_nn)
print("\nConfusion Matrix: \n", confusion_matrix_nn)

"""# **Export Model**"""

import pickle

with open('logreg_model.pkl', 'wb') as f:
    pickle.dump(logreg, f)

with open('nn_model.pkl', 'wb') as f:
    pickle.dump(nn_model, f)